### ISSUE TITLE
You need a CA server (you can add it through the web admin)

### ISSUE THREAD

**Issue by baboonandsloth** [YunoHost-Apps/vpnclient_ynh#100]
I think I set everything up right and I import the config file and then get this:
Starting YunoHost VPN Client....
[CRIT] You need a CA server (you can add it through the web admin)
ynh-vpnclient.service: Main process exited, code=exited, status=1/FAILURE
ynh-vpnclient.service: Failed with result 'exit-code'.
Failed to start YunoHost VPN Client..
Starting YunoHost VPN Client....
[CRIT] You need a CA server (you can add it through the web admin)
ynh-vpnclient.service: Main process exited, code=exited, status=1/FAILURE
ynh-vpnclient.service: Failed with result 'exit-code'.
Failed to start YunoHost VPN Client..
Starting YunoHost VPN Client....
[CRIT] You need a CA server (you can add it through the web admin)
ynh-vpnclient.service: Main process exited, code=exited, status=1/FAILURE
ynh-vpnclient.service: Failed with result 'exit-code'.
Failed to start YunoHost VPN Client..

I don't know what this means, any idea/help?

**Comment by JacquelinDV** [comment]
Bonsoir,
I have the same problem with a RPI3+ and Aquilenet as VPN furnished!
????
Quelle manip faut-il faoire pour passer cette étyape?

**Comment by jerometerrier** [comment]
Bonsoir 
je crois qu'il y a un problème avec le script qui split le fichier ovpn.
Si vous ouvrez le fichier 
`/etc/openvpn/client.conf`
vous verrez qu'à la fin du fichier, il est possible que vous ayez 
```
</tls-crypt> ca 
/etc/openvpn/keys/ca-server.crt

```

au lieu de 

```
</tls-crypt>
ca /etc/openvpn/keys/ca-server.crt
```

Il suffit de faire 
`sudo nano /etc/openvpn/client.conf`

et faire un retour à la ligne après `</tls-crypt>` pour que cela fonctionne.
je vais regarder pour modifier le script en conséquence.
Bonne soirée
