### ISSUE TITLE
Perform network throughput tests

### ISSUE THREAD

**Issue by jvaubourg** [YunoHost-Apps/vpnclient_ynh#13]
This app can be used as a wifi/internet hotspot, thanks to the  [Wifi Hotspot app](https://github.com/jvaubourg/hotspot_ynh). Many people ask us about the flow loss when using the VPN for accessing to the internet.

We should propose some charts "with an without a VPN", and especially with the [Olimex LIME](https://www.olimex.com/Products/OLinuXino/A20/A20-OLinuXino-LIME/open-source-hardware) and [LIME2](https://www.olimex.com/Products/OLinuXino/A20/A20-OLinuXIno-LIME2/open-source-hardware) (used in the [Internet Cube](http://labriqueinter.net) project).

**Comment by hidrarga** [comment]
That's a nice idea, but I don't think we have enough energy to implement this :/ So I'm closing this issue…
