### ISSUE TITLE
Import ovpn file? (ProtonVPN)

### ISSUE THREAD

**Issue by roukydesbois** [YunoHost-Apps/vpnclient_ynh#49]
Hello!

I'm trying to get vpnclient to use ProtonVPN. They provide an ovpn configuration file - as OpenVPN runs behind vpnclient, would it be possible to import this file rather than entering all the fields one by one?

Thanks!

**Comment by pitchum** [comment]
Unfortunately this is not possible (yet?).
You may want to craft your own dotcube file by following the [specifications](https://internetcu.be/dotcubefiles.html).

As a side note beware that if your VPN provider does not provide a static IPv4 address you won't be able to make proper use of most apps available in yunohost.
I have no clue if ProtonVPN provides static IP addresses.

**Comment by roukydesbois** [comment]
Yes I had seen the specifications, but I'm not sure I can map everything coming from the ovpn file from ProtonVPN to them. I'll give it a try :)

As for the use of yunohost apps, I'm aware of this and it's not an issue as I want to use the RPI I'm configuring as an AP easy to take with me while travelling, I have a more stable one with static IP and all!

**Comment by zamentur** [comment]
ProtonVPN seems not providing public dedicated ip and port forwarding feature. This vpn is not made to self-host yourself, it's a privacy vpn.
