### ISSUE TITLE
Import ovpn file? (PureVPN) 

### ISSUE THREAD

**Issue by mario26** [YunoHost-Apps/vpnclient_ynh#62]
Hello!

I want to use PureVPN, it provides static IP, but i can't get the VPN to work on the server. I tried to set up a ".cube" file following the [specifications](https://internetcu.be/dotcubefiles.html) but it does not work, i do not understand my error... ?!

Can you give me a sample configuration for PureVPN?

PureVPN "ovpn" files can be found here: [New+OVPN+Files](https://s3-us-west-1.amazonaws.com/heartbleed/windows/New+OVPN+Files.zip)

Thanks in advance !

**Comment by tutle** [comment]
Not sure it's possible to use pure vpn, check tunnel is visible and port opened, I tryed cyberghost with static IP, failed..

**Comment by JOduMonT** [comment]
I confirm, being able to import opvn file would be wonderfull

**Comment by randomstuff** [comment]
Alternatively, a separate conversion script could be written.

**Comment by randomstuff** [comment]
I guess the main problem is that some parameters which are expected to be configured by the vpnclient_ynh application are typically not present in .ovpn files but dynamically pushed by the server:

* resolvers (probably not a big problem);
* static IPv4 and IPv6 (YunoHost need those for configuring DNS entries).

A solution would be to connect a first time and retrieve these values (assuming they are not dynamic).

As a bonus, directly using .ovpn files could be used to provide more advanced configurations. For example, attempting several connection methods:

~~~
  <connection>
  remote vpn.example.com 1194 udp
  explicit-exit-notify
  </connection>
  
  <connection>
  remote vpn.example.com 443 udp
  explicit-exit-notify
  </connection>
  
  <connection>
  remote vpn.example.com 43 udp
  explicit-exit-notify
  </connection>
  
  <connection>
  remote vpn.example.com 1194 tcp
  </connection>
  
  <connection>
  remote vpn.example.com 443 tcp
  </connection>
  
  <connection>
  remote vpn.example.com 43 tcp
  </connection>
~~~

**Comment by zamentur** [comment]
Convert a ovpn is a solution, however the .cube is dedicated to vpn compatible with self-hosting.

If we support ovpn, a lot of persons will buy classic vpn and don't understand why it doesn't work.



> Not sure it's possible to use pure vpn, check tunnel is visible and port opened, I tryed cyberghost with static IP, failed..

We are creating a list of compatible vpn providers. About commercial vpn provider, we should do some tests.

**Comment by zamentur** [comment]
I finally decided to support ovpn file in the new config panel...
See https://github.com/labriqueinternet/vpnclient_ynh/pull/65

**Comment by zamentur** [comment]
You can now try to use your ovpn directly.

We don't know if purevpn is compatible however you can now find a compatible vpn providers list here: https://yunohost.org/en/providers/vpn
