### ISSUE TITLE
Script that check if VPN is up, restart VPN if needed

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/vpnclient_ynh#69]
Hello,

It happened to me several time these last days (it was not happening before yunohost 4) that my VPN stop working and I need to restart ynh-vpnclient manually (connecting by ssh on local ip address).
I adapted a script to check if VPN is up and if not to restart the service. I added a reboot also but I'm not sure it's a good idea, let me know.

It's here : https://forum.yunohost.org/t/ynh-vpnclient-checker-ne-semble-pas-fonctionner/12634/2

**Comment by alexAubin** [comment]
Possible exlanation of the issue, which imho is related to the fact that @Thatoo has no IPv4 if the VPN ain't up, therefore DNS resolution is broken because only IPv4 resolvers are defined ?

https://forum.yunohost.org/t/ynh-vpnclient-checker-ne-semble-pas-fonctionner/12634/4?u=aleks

**Comment by hidrarga** [comment]
There is already a script to check if the VPN is up. As Aleks suggested, the problem might be due to the DNS resolver…
