### ISSUE TITLE
Update PHP version

### ISSUE THREAD

**Issue by MCMic** [YunoHost-Apps/vpnclient_ynh#73]
This app is depending upon PHP 7.0, while buster have PHP 7.3 by default.

7.0 is not supported anymore by the PHP project: https://www.php.net/supported-versions.php

What is the reason for the hard requirement on PHP 7.0, could this be made generic to just require PHP?

**Comment by pitchum** [comment]
Maybe we could declare a dependency on package `php-fpm` instead of `php7.0-fpm`.
But then the scripts need reworking because they explicitly invoke the php7.0-fpm systemd unit.
For example in [scripts/install](https://github.com/labriqueinternet/vpnclient_ynh/blob/master/scripts/install#L92):

    systemctl restart php7.0-fpm

**Comment by tutle** [comment]
While trying to install vpnclient_ynh , big crash. no more access trough web, ssh..
Need to log directly to the server and then uninstall vpnclient (it says impossible, but after 2 reboot, vpnclient not exist anymore everything is ok again)
https://paste.yunohost.org/raw/hixuraseta
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 489, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 588, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/log.py", line 225, in log_display
    if 'log_path' in metadata:
TypeError: argument of type 'NoneType' is not iterable
Ces services requis doivent être en cours d’exécution pour exécuter cette action : php7.3-fpm

**Comment by zamentur** [comment]
unrelevant anymore
