### ISSUE TITLE
Failed VPN connection (Neutrinet)

### ISSUE THREAD

**Issue by dhuschde** [YunoHost-Apps/vpnclient_ynh#81]
### Describe the bug

I tried to use the VPN, as my Network doesn't allow Port forwarding...
I wanted to use Neutrinet, as you said, it should work.
Sadly, I get this error: [Logs](https://paste.yunohost.org/cabinumeye)
![image](https://user-images.githubusercontent.com/85834680/137963434-48f24c2d-17f0-4e52-83a6-20121ce3f8b4.png)

I already tried this [Tutorial: (used with Google Translate, as I can't speak Frensh)](https://neutrinet-be.translate.goog/fr/blog/yunohost-et-vpn?_x_tr_sl=fr&_x_tr_tl=en&_x_tr_hl=de&_x_tr_pto=nui)

### Context

- Hardware: Old laptop or computer (64)
- YunoHost version: 4.2.8.3 (stable)
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen | ...
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 
- Using, or trying to install package version/branch: 1.4.1~ynh3

**Comment by dhuschde** [comment]
Failed with this Log: https://paste.yunohost.org/ojoyamicew

**Comment by zamentur** [comment]
COuld you try again with the new vpnclient 2.0 version (with yunohost 4.3) ?

**Comment by dhuschde** [comment]
Still the same…

**Comment by alexAubin** [comment]
Uuuuuuh wut, what are those @font-face thingies ...

**Comment by dhuschde** [comment]
That's Windows Mail...
The Program, that never works...

But I wanted to say, that it still doesn't work.
