### ISSUE TITLE
VPN client can’t be displayed as a tile on user portal

### ISSUE THREAD

**Issue by pagiraud** [YunoHost-Apps/vpnclient_ynh#86]
Hi,
My Yunohost is in French, so maybe I don’t use the right terms.
On the admin panel of the app, an option is "Visible en tuile dans le portail utilisateur". I guess it is something like "Displayed as a tile on the user portal". I tried several times to activate / deactivate it, logged out and in several times but nothing appeared on my user portal.
I don’t really get the point of this option, but I think it doesn’t work, at least from the Web UI.

**Comment by alexAubin** [comment]
Starting with version 2.0 of this app, it's not available anymore as a classic webapp (as it was before) but only as a config panel in the webadmin

The fact that you still get the option to enable the portal tile is a display ~bug (most of apps are classic webapp so we didn't really thought about that case, so to be removed later)
