### ISSUE TITLE
VPN Client app configure results in "'service_enabled' should be initialized with a value during install or upgrade."

### ISSUE THREAD

**Issue by mikerjensen** [YunoHost-Apps/vpnclient_ynh#89]
I have had the Open VPN client app already installed but had not tried to use it yet. I upgraded to YH version 4.3.3 and after the upgrade I tried to access the VPN client config panel from app configuration screen and got: 
Error: "500" Internal Server Error, 
Action: "GET" /yunohost/api/apps/vpnclient/config-panel?full&locale=en
Error message:
Config panel question 'service_enabled' should be initialized with a value during install or upgrade.

Another issue is that clicking OK after receiving the message doesn't seem to do anything.   I.e the warning message won't go away  even if i try to go another menu option, unless I log out.

**Comment by hidrarga** [comment]
I'm closing, but feel free to comment if the issue still occur with Yunohost 11…
