### ISSUE TITLE
Automatically find a port

### ISSUE THREAD

**Issue by jvaubourg** [YunoHost-Apps/vpnclient_ynh#9]
The user can configure a port in the web admin, for contacting the VPN server. But, some internet access are very filtered and the port is not always available. On the other hand, the VPN server can be configured to listen on all ports with UDP and TCP. The user has then to find the correct couple protocol/port, working with the current Internet access.

The service should automatically find this port, by sequentially trying:
1. the default UDP/TCP port configured thanks to the web admin
2. UDP/53
3. TCP/443
4. TCP/80
5. others?

**Comment by randomstuff** [comment]
I wonder if the NTP port might not be a good candidate.

**Comment by randomstuff** [comment]
By the way this can be achieved [super easily](https://wiki-adh.fdn.fr/travaux:vpn_misc:doc:openvpn:config) from the openVPN config file:

    <connection>
    remote vpn.example.com 1194 udp
    explicit-exit-notify
    </connection>
    <connection>
    remote vpn.example.com 1194 tcp
    </connection>
    ...

**Comment by hidrarga** [comment]
The general use case is that the VPN provider gives the port and address, so IMHA there is no need to find the port automatically. Also, this would make the app more complex than necessary.
